# app/config/config.yml
# (or config/packages/stof_doctrine_extensions.yaml if you use Flex)
stof_doctrine_extensions:
    default_locale: en_US
    orm:
        default:
            softdeleteable: true
        #     tree: true
        #     timestampable: false # not needed: listeners are not enabled by default
        # other:
        #     timestampable: true